### ISSUE TITLE
로그인 성공 안되는 이유 : .decode('utf-8').

### ISSUE THREAD

**Issue by codesejin** [codesejin/pyjwt_login-signup#1]
`127.0.0.1 - - [05/Aug/2022 01:24:25] "POST /api/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Desktop\sparta_plus\project04\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\admin\Desktop\sparta_plus\project04\app.py", line 95, in api_login
    token = jwt.encode(payload, SECRET_KEY, algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'`

![image](https://user-images.githubusercontent.com/101460733/182903236-b34ff5e2-bfd2-418b-843d-d4ce4a120db7.png)

**Comment by codesejin** [comment]
`    if result is not None:
        # JWT 토큰에는, payload와 시크릿키가 필요합니다.
        # 시크릿키가 있어야 토큰을 디코딩(=풀기) 해서 payload 값을 볼 수 있습니다.
        # 아래에선 id와 exp를 담았습니다. 즉, JWT 토큰을 풀면 유저ID 값을 알 수 있습니다.
        # exp에는 만료시간을 넣어줍니다. 만료시간이 지나면, 시크릿키로 토큰을 풀 때 만료되었다고 에러가 납니다.
        payload = {
            'id': id_receive,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(seconds=3)
        }
        token = jwt.encode(payload, SECRET_KEY, algorithm='HS256').decode('utf-8').

        # token을 줍니다.
        return jsonify({'result': 'success', 'token': token})
    # 찾지 못하면
    else:
        return jsonify({'result': 'fail', 'msg': '아이디/비밀번호가 일치하지 않습니다.'})`

**Comment by codesejin** [comment]
` # 찾으면 JWT 토큰을 만들어 발급합니다.
    if result is not None:
        # JWT 토큰에는, payload와 시크릿키가 필요합니다.
        # 시크릿키가 있어야 토큰을 디코딩(=풀기) 해서 payload 값을 볼 수 있습니다.
        # 아래에선 id와 exp를 담았습니다. 즉, JWT 토큰을 풀면 유저ID 값을 알 수 있습니다.
        # exp에는 만료시간을 넣어줍니다. 만료시간이 지나면, 시크릿키로 토큰을 풀 때 만료되었다고 에러가 납니다.
        payload = {
            'id': id_receive,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(seconds=5)
        }
        token = jwt.encode(payload, SECRET_KEY, algorithm='HS256').decode('utf-8')

        # token을 줍니다.
        return jsonify({'result': 'success', 'token': token})
    # 찾지 못하면
    else:
        return jsonify({'result': 'fail', 'msg': '아이디/비밀번호가 일치하지 않습니다.'})`

**Comment by codesejin** [comment]
`token = jwt.encode(payload, SECRET_KEY, algorithm='HS256').decode('utf-8')`

해당부분에서 .decode('utf-8') 제외하고 푸시한 상황
